### ISSUE TITLE
Windows and glEnd(GL_QUADS) TypeError

### ISSUE THREAD

**Issue by beduffy** [maximecb/gym-miniworld#11]
Hello, I installed on windows 10 and got this error from running manual_control.py or run_tests.py. Does it only work on linux? I'll try that soon as well.

```
Traceback (most recent call last):
  File "run_tests.py", line 9, in <module>
    env = gym.make('MiniWorld-Hallway-v0')
  File "C:\Users\benjamin.duffy\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "C:\Users\benjamin.duffy\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "C:\Users\benjamin.duffy\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\gym\envs\registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "C:\Users\benjamin.duffy\all_projects\gym-miniworld\gym_miniworld\envs\hallway.py", line 19, in __init__
    **kwargs
  File "C:\Users\benjamin.duffy\all_projects\gym-miniworld\gym_miniworld\miniworld.py", line 524, in __init__
    self.reset()
  File "C:\Users\benjamin.duffy\all_projects\gym-miniworld\gym_miniworld\miniworld.py", line 589, in reset
    obs = self.render_obs()
  File "C:\Users\benjamin.duffy\all_projects\gym-miniworld\gym_miniworld\miniworld.py", line 1197, in render_obs
    render_agent=False
  File "C:\Users\benjamin.duffy\all_projects\gym-miniworld\gym_miniworld\miniworld.py", line 1071, in _render_world
    ent.render()
  File "C:\Users\benjamin.duffy\all_projects\gym-miniworld\gym_miniworld\entity.py", line 429, in render
    glEnd(GL_QUADS)
TypeError: this function takes 0 arguments (1 given)
```

**Comment by maximecb** [comment]
This is a bug, the calls to glEnd are incorrect, but for some reason it doesn't complain on Linux!

I pushed a commit to fix this. Thanks for opening an issue @beduffy, otherwise I might never have known!
