### ISSUE TITLE
Running over SSH

### ISSUE THREAD

**Issue by mklissa** [maximecb/gym-miniworld#13]
Hi there,
I am trying to run the environment over ssh on a linux server where I don't have sudo rights, and I'm getting this error:
```
~/gym-miniworld/pytorch-a2c-ppo-acktr $ python main.py --algo ppo --num-frames 5000000 --num-processes 16 --num-steps 80 --lr 0.00005 --env-name MiniWorld-Hallway-v0
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from envs import make_vec_envs
  File "/home/ml/mklissa/gym-miniworld/pytorch-a2c-ppo-acktr/envs.py", line 28, in <module>
    import gym_miniworld
  File "/home/ml/mklissa/gym-miniworld/gym_miniworld/__init__.py", line 1, in <module>
    from . import miniworld
  File "/home/ml/mklissa/gym-miniworld/gym_miniworld/miniworld.py", line 7, in <module>
    from .opengl import *
  File "/home/ml/mklissa/gym-miniworld/gym_miniworld/opengl.py", line 5, in <module>
    from pyglet.gl import *
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1845, in get_default_display
    return pyglet.canvas.get_display()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 86, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```
I'm not too sure how to resolve this

Thanks!

**Comment by maximecb** [comment]
Hi Martin,

In order to train over SSH, you need to [create a virtual frame buffer](https://github.com/maximecb/gym-miniworld/blob/master/docs/troubleshooting.md#nosuchdisplayexception-cannot-connect-to-none) to render into. This can be done using `xvfb-run`.

Example command: `xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" python3 main.py --algo ppo --num-processes 16 --num-steps 80 --lr 0.00005 --env-name MiniWorld-Hallway-v0`

If this doesn't work, or `xvfb-run` isn't installed on the machines where you are training, you will need to communicate with the administrators and get them to install it. It's a fairly standard tool.

**Comment by mklissa** [comment]
Hi Maxime,
thank you for the fast response. It does seem to resolve the previous error, but I now get this message:

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from envs import make_vec_envs
  File "/home/ml/mklissa/gym-miniworld/pytorch-a2c-ppo-acktr/envs.py", line 28, in <module>
    import gym_miniworld
  File "/home/ml/mklissa/gym-miniworld/gym_miniworld/__init__.py", line 1, in <module>
    from . import miniworld
  File "/home/ml/mklissa/gym-miniworld/gym_miniworld/miniworld.py", line 7, in <module>
    from .opengl import *
  File "/home/ml/mklissa/gym-miniworld/gym_miniworld/opengl.py", line 5, in <module>
    from pyglet.gl import *
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/__init__.py", line 571, in __init__
    self._create()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 263, in _create
    self.context.attach(self.canvas)
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 323, in attach
    self.set_current()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 328, in set_current
    super(XlibContext13, self).set_current()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/base.py", line 301, in set_current
    gl_info.set_active_context()
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/gl_info.py", line 98, in set_active_context
    if self.have_version(3):
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/gl_info.py", line 170, in have_version
    imajor, iminor, irelease = [int(v) for v in ver.split('.', 3)[:3]]
  File "/home/ml/mklissa/miniconda2/envs/kag/lib/python3.6/site-packages/pyglet/gl/gl_info.py", line 170, in <listcomp>
    imajor, iminor, irelease = [int(v) for v in ver.split('.', 3)[:3]]
ValueError: invalid literal for int() with base 10: ''
```
This is obtained after running the example command in your response.

**Comment by maximecb** [comment]
Try running `glxinfo`, as described in here: https://github.com/openai/gym/issues/439

**Comment by mklissa** [comment]
Oh okay, that explains it. However `glxinfo` is not installed on the school's server I am trying to run the code. I will ask for it to be installed. Thank you for your help!

**Comment by maximecb** [comment]
That probably means glx is not installed. Best of luck!

**Comment by psurya1994** [comment]
Thanks, `xvfb-run` suggestion was helpful Maxime! Is there a way to run this on a jupyter notebook on the server too?

**Comment by maximecb** [comment]
What do you need to run something inside a jupyter notebook? I'm assuming it would be a matter of running your server-side program using `xvfb-run`?

**Comment by psurya1994** [comment]
I run my algorithms in jupyter notebook because that makes it easier to debug; but running `import gym_miniworld` gives me the same error as above. 

You're suggesting that I run the jupyter notebook with `xvfb-run`, I will try that.
