### ISSUE TITLE
Empty chunks & faces variable when executing run_tests.py

### ISSUE THREAD

**Issue by TexMex657** [maximecb/gym-miniworld#20]
When script gets to PickupObjs environment, end up getting an index error since chunks variable in objmesh.py never gets anything successfully appended. Looks like the faces variable also ends up empty in this case. 

```
Testing "MiniWorld-CollectHealth-v0"
Testing "MiniWorld-FourRooms-v0"
Testing "MiniWorld-Hallway-v0"
Testing "MiniWorld-Maze-v0"
Testing "MiniWorld-MazeS2-v0"
Testing "MiniWorld-MazeS3-v0"
Testing "MiniWorld-MazeS3Fast-v0"
Testing "MiniWorld-OneRoom-v0"
Testing "MiniWorld-OneRoomS6-v0"
Testing "MiniWorld-OneRoomS6Fast-v0"
Testing "MiniWorld-PickupObjs-v0"
Traceback (most recent call last):
  File "run_tests.py", line 53, in <module>
    env = gym.make(env_id)
  File "C:\Users\texmex657\AppData\Local\conda\conda\envs\dto\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\texmex657\AppData\Local\conda\conda\envs\dto\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\texmex657\AppData\Local\conda\conda\envs\dto\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\texmex657\git\gym_miniworld\envs\pickupobjs.py", line 20, in __init__
    **kwargs
  File "C:\Users\texmex657\git\gym_miniworld\miniworld.py", line 523, in __init__
    self.reset()
  File "C:\Users\texmex657\git\gym_miniworld\miniworld.py", line 555, in reset
    self._gen_world()
  File "C:\Users\texmex657\git\gym_miniworld\envs\pickupobjs.py", line 48, in _gen_world
    self.place_entity(Key(color=color))
  File "C:\Users\texmex657\git\gym_miniworld\entity.py", line 420, in __init__
    static=False
  File "C:\Users\texmex657\git\gym_miniworld\entity.py", line 119, in __init__
    self.mesh = ObjMesh.get(mesh_name)
  File "C:\Users\texmex657\git\gym_miniworld\objmesh.py", line 28, in get
    mesh = ObjMesh(file_path)
  File "C:\Users\texmex657\git\gym_miniworld\objmesh.py", line 128, in __init__
    chunks[-1]['end_idx'] = len(faces)
IndexError: list index out of range

```

**Comment by maximecb** [comment]
Hi @TexMex657 ! Thanks for reporting this issue.

I unfortunately can't replicate this bug on Linux. If I had to guess, I think it might have something to do with the way files are handled (different line terminators on Windows maybe?). I don't have Windows here so I can't debug this issue easily. Could you help me track down the problem?

I suspect that no faces are loaded. I would suggest putting a print statement on line 101 to log it when a face gets parsed:
https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/objmesh.py#L101

You could also put a print statement on line 76 to print out the tokens for each line, to see if we can spot what's wrong: https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/objmesh.py#L76

Can you do that and report what gets printed? Your help is much appreciated.

**Comment by maximecb** [comment]
@TexMex657 have you had a chance to look at this again?

**Comment by TexMex657** [comment]
Not yet. I'll try & get to it tonight.

**Comment by TexMex657** [comment]
Is there supposed to a faces of objects loaded for every environment or only those with mesh objects? Looks like collect health environment works fine, but the ball object for some reason doesn't load any faces causing the error

```
(dto) C:\Users\texmex657\git\gym-miniworld\>python run_tests.py
Testing "MiniWorld-CollectHealth-v0"

...

tokens: ['f', '89/213/3', '86/224/3', '91/225/3']

prefix == f; adding face...
Current len(faces): 165

Testing "MiniWorld-FourRooms-v0"
Testing "MiniWorld-Hallway-v0"
Testing "MiniWorld-Maze-v0"
Testing "MiniWorld-MazeS2-v0"
Testing "MiniWorld-MazeS3-v0"
Testing "MiniWorld-MazeS3Fast-v0"
Testing "MiniWorld-OneRoom-v0"
Testing "MiniWorld-OneRoomS6-v0"
Testing "MiniWorld-OneRoomS6Fast-v0"
Testing "MiniWorld-PickupObjs-v0"

tokens: ['ball.obj']
Traceback (most recent call last):
  File "C:\Users\texmex657\git\gym-miniworld\run_tests.py", line 53, in <module>
    env = gym.make(env_id)
  File "C:\Users\texmex657\AppData\Local\conda\conda\envs\dto\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\texmex657\AppData\Local\conda\conda\envs\dto\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\texmex657\AppData\Local\conda\conda\envs\dto\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\envs\pickupobjs.py", line 20, in __init__
    **kwargs
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\miniworld.py", line 523, in __init__
    self.reset()
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\miniworld.py", line 555, in reset
    self._gen_world()
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\envs\pickupobjs.py", line 46, in _gen_world
    self.place_entity(Ball(color=color, size=0.9))
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\entity.py", line 433, in __init__
    static=False
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\entity.py", line 119, in __init__
    self.mesh = ObjMesh.get(mesh_name)
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\objmesh.py", line 28, in get
    mesh = ObjMesh(file_path)
  File "C:\Users\texmex657\git\gym-miniworld\gym_miniworld\objmesh.py", line 131, in __init__
    chunks[-1]['end_idx'] = len(faces)
IndexError: list index out of range
```

**Comment by maximecb** [comment]
I found the problem. The repository has symbolic links in it. The `ball_red.obj`, `ball_blue.obj` etc all point to `ball.obj`. This works fine on Linux, but on Windows, this is the behavior: https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

I just pushed a commit which should fix the issue. Let me know if it works!

**Comment by TexMex657** [comment]
Yup, looks like it fully executes now!

```
python run_tests.py
Testing "MiniWorld-CollectHealth-v0"
Testing "MiniWorld-FourRooms-v0"
Testing "MiniWorld-Hallway-v0"
Testing "MiniWorld-Maze-v0"
Testing "MiniWorld-MazeS2-v0"
Testing "MiniWorld-MazeS3-v0"
Testing "MiniWorld-MazeS3Fast-v0"
Testing "MiniWorld-OneRoom-v0"
Testing "MiniWorld-OneRoomS6-v0"
Testing "MiniWorld-OneRoomS6Fast-v0"
Testing "MiniWorld-PickupObjs-v0"
Testing "MiniWorld-PutNext-v0"
Testing "MiniWorld-RoomObjs-v0"
Testing "MiniWorld-Sidewalk-v0"
Testing "MiniWorld-SimToRealGoTo-v0"
Testing "MiniWorld-SimToRealPush-v0"
Testing "MiniWorld-TMaze-v0"
Testing "MiniWorld-ThreeRooms-v0"
Testing "MiniWorld-WallGap-v0"
```
