### ISSUE TITLE
assert res == GL_FRAMEBUFFER_COMPLETE

### ISSUE THREAD

**Issue by lcswillems** [maximecb/gym-miniworld#4]
I want to make my Pytorch-a2c-ppo work for your environment.

I cloned and installed the package but when I do:

```./manual_control.py --env-name MiniWorld-Hallway-v0```

I get this:

```
Registered env: MiniWorld-CollectHealth-v0
Registered env: MiniWorld-FourRooms-v0
Registered env: MiniWorld-Hallway-v0
Registered env: MiniWorld-Maze-v0
Registered env: MiniWorld-MazeS3-v0
Registered env: MiniWorld-OneRoom-v0
Registered env: MiniWorld-PutNext-v0
Registered env: MiniWorld-TMaze-v0
Registered env: MiniWorld-ThreeRooms-v0
Registered env: MiniWorld-WallGap-v0
Traceback (most recent call last):
  File "./manual_control.py", line 23, in <module>
    env = gym.make(args.env_name)
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/envs/oneroom.py", line 18, in __init__
    **kwargs
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/miniworld.py", line 517, in __init__
    self.obs_fb = FrameBuffer(obs_width, obs_height, 8)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/opengl.py", line 183, in __init__
    assert res == GL_FRAMEBUFFER_COMPLETE
AssertionError
```

Do you know what I did wrong?

**Comment by maximecb** [comment]
:O 

Seems there's some issue with OpenGL drivers. Are you running Mac/Linux? What kind of GPU?

**Comment by lcswillems** [comment]
I am running on Linux. For the GPU, I don't really know.

If I execute `sudo lshw -C display`, I get: 

```
  *-display                 
       description: VGA compatible controller
       product: 4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:30 memory:f7800000-f7bfffff memory:e0000000-efffffff ioport:f000(size=64) memory:c0000-dffff
```

I don't know if it helps...

**Comment by maximecb** [comment]
Yes that is useful. Your GPU is the one that comes built into your Intel CPU. The driver you use is probably the default one that comes with Linux.

I added some extra debugging code which will hopefully give us more information about the specific frame buffer error that happened. Could you do a `git pull` and run it again?

**Comment by lcswillems** [comment]
```
gym-miniworld$ ./manual_control.py --env-name MiniWorld-Hallway-v0Registered env: MiniWorld-CollectHealth-v0
Registered env: MiniWorld-FourRooms-v0
Registered env: MiniWorld-Hallway-v0
Registered env: MiniWorld-Maze-v0
Registered env: MiniWorld-MazeS3-v0
Registered env: MiniWorld-OneRoom-v0
Registered env: MiniWorld-PutNext-v0
Registered env: MiniWorld-TMaze-v0
Registered env: MiniWorld-ThreeRooms-v0
Registered env: MiniWorld-WallGap-v0
Traceback (most recent call last):
  File "./manual_control.py", line 23, in <module>
    env = gym.make(args.env_name)
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/envs/hallway.py", line 19, in __init__
    **kwargs
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/miniworld.py", line 517, in __init__
    self.obs_fb = FrameBuffer(obs_width, obs_height, 8)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/opengl.py", line 196, in __init__
    assert res == GL_FRAMEBUFFER_COMPLETE, FB_ERROR_ENUMS.get(res, res)
AssertionError: GL_FRAMEBUFFER_UNSUPPORTED
```

**Comment by maximecb** [comment]
Okay, might be making progress :)

I added an extra check. Could you please try running it once more.

Then, if it doesn't work, can you try:
1. Setting `num_samples = 1` before the try block.
2. Replacing this line with just `assert False`: https://github.com/maximecb/gym-miniworld/blob/master/gym_miniworld/opengl.py#L134 

I'd like to know if either of these fix the problem. Sorry this is taking multiple iterations to debug.

**Comment by lcswillems** [comment]
This works when I do the modifications 1. and 2. you suggest.

![image](https://user-images.githubusercontent.com/5437552/48280303-83d51b00-e453-11e8-9d07-32d9691dd5ba.png)

**Comment by lcswillems** [comment]
I keep trying to make your repository working for mine, but now, I have a new bug:

```
torch-rl$ python -m scripts.train --algo ppo --env MiniWorld-Hallway-v0
Registered env: MiniWorld-CollectHealth-v0
Registered env: MiniWorld-FourRooms-v0
Registered env: MiniWorld-Hallway-v0
Registered env: MiniWorld-Maze-v0
Registered env: MiniWorld-MazeS3-v0
Registered env: MiniWorld-OneRoom-v0
Registered env: MiniWorld-PutNext-v0
Registered env: MiniWorld-TMaze-v0
Registered env: MiniWorld-ThreeRooms-v0
Registered env: MiniWorld-WallGap-v0
/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/scripts/train.py --algo ppo --env MiniWorld-Hallway-v0

Namespace(algo='ppo', batch_size=256, clip_eps=0.2, discount=0.99, entropy_coef=0.01, env='MiniWorld-Hallway-v0', epochs=4, frames=10000000,frames_per_proc=None, gae_lambda=0.95, instr=False, log_interval=1, lr=0.0007, max_grad_norm=0.5, mem=False, model=None, optim_alpha=0.99, optim_eps=1e-05, procs=16, recurrence=1, save_interval=0, seed=1, tb=False, value_loss_coef=0.5)

loading texture "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/textures/concrete_1.png"
loading texture "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/textures/floor_tiles_bw_1.png"
loading texture "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/textures/concrete_tiles_1.png"
Model successfully created

ACModel(
  (image_conv): Sequential(
    (0): Conv2d(3, 16, kernel_size=(2, 2), stride=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(16, 32, kernel_size=(2, 2), stride=(1, 1))
    (4): ReLU()
    (5): Conv2d(32, 64, kernel_size=(2, 2), stride=(1, 1))
    (6): ReLU()
  )
  (actor): Sequential(
    (0): Linear(in_features=63936, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=3, bias=True)
  )
  (critic): Sequential(
    (0): Linear(in_features=63936, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
)

CUDA available: False

bonjour
i965: Failed to submit batchbuffer: Invalid argument
i965: Failed to submit batchbuffer: Invalid argument
i965: Failed to submit batchbuffer: Invalid argument
bonjour
Traceback (most recent call last):
  File "/home/lcswillems/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lcswillems/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/scripts/train.py", line 152, in <module>
    logs = algo.update_parameters()
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/algos/ppo.py", line 32, in update_parameters
    exps, logs = self.collect_experiences()
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/algos/base.py", line 136, in collect_experiences
    obs, reward, done, _ = self.env.step(action.cpu().numpy())
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/utils/penv.py", line 50, in step
    results = zip(*[(obs, reward, done, info)] + [local.recv() for local in self.locals])
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/utils/penv.py", line 50, in <listcomp>
    results = zip(*[(obs, reward, done, info)] + [local.recv() for local in self.locals])
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

It seems there is a problem with multiprocessing and OpenGL, especially when the subprocesses try to communicate with the parent.

**Comment by maximecb** [comment]
Great that you got the graphics working. I will try to come up with a cleaner fix for that.

For the second issue, thankfully, I already have a workaround. You have to set the fork method to 'forkserver':

https://github.com/maximecb/gym-miniworld/blob/master/pytorch-a2c-ppo-acktr/vec_env/subproc_vec_env.py#L2
https://github.com/maximecb/gym-miniworld/blob/master/pytorch-a2c-ppo-acktr/vec_env/subproc_vec_env.py#L39

This changes something in the way resources are shared between subprocesses I believe.

**Comment by lcswillems** [comment]
I now have this bug:

```
Traceback (most recent call last):
  File "/home/lcswillems/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lcswillems/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/scripts/train.py", line 138, in <module>
    args.optim_eps, args.clip_eps, args.epochs, args.batch_size, preprocess_obss)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/algos/ppo.py", line 18, in __init__
    value_loss_coef, max_grad_norm, recurrence, preprocess_obss, reshape_reward)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/algos/base.py", line 49, in __init__
    self.env = ParallelEnv(envs)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/torch-rl/torch_rl/torch_rl/utils/penv.py", line 35, in __init__
    p.start()
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/home/lcswillems/miniconda3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
ValueError: ctypes objects containing pointers cannot be pickled
```

**Comment by maximecb** [comment]
This I'm not sure about. Are you trying to pickle the whole env or something?

**Comment by maximecb** [comment]
@lcswillems I added a check to the frame buffer to automatically get the maximum number of samples supported. Does this allow you to run `manual_control.py` without modifications?

**Comment by lcswillems** [comment]
No, it doesn't work... Here is the error:

```
gym-miniworld$ ./manual_control.py --env-name MiniWorld-Hallway-v0
Registered env: MiniWorld-CollectHealth-v0
Registered env: MiniWorld-FourRooms-v0
Registered env: MiniWorld-Hallway-v0
Registered env: MiniWorld-Maze-v0
Registered env: MiniWorld-MazeS3-v0
Registered env: MiniWorld-OneRoom-v0
Registered env: MiniWorld-PutNext-v0
Registered env: MiniWorld-TMaze-v0
Registered env: MiniWorld-ThreeRooms-v0
Registered env: MiniWorld-WallGap-v0
Traceback (most recent call last):
  File "./manual_control.py", line 23, in <module>
    env = gym.make(args.env_name)
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/lcswillems/miniconda3/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/envs/hallway.py", line 19, in __init__
    **kwargs
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/miniworld.py", line 517, in __init__
    self.obs_fb = FrameBuffer(obs_width, obs_height, 8)
  File "/mnt/Data/Documents/Education/2017 2018 - M1/Stage/Code/gym-miniworld/gym_miniworld/opengl.py", line 208, in __init__
    assert res == GL_FRAMEBUFFER_COMPLETE, FB_ERROR_ENUMS.get(res, res)
AssertionError: GL_FRAMEBUFFER_UNSUPPORTED
```

In the `opengl.py` file, you have `);` at the end of some lines.

**Comment by lcswillems** [comment]
Yes!! This works now :)

**Comment by maximecb** [comment]
Wonderful.

**Comment by lcswillems** [comment]
> Great that you got the graphics working. I will try to come up with a cleaner fix for that.
> 
> For the second issue, thankfully, I already have a workaround. You have to set the fork method to 'forkserver':
> 
> https://github.com/maximecb/gym-miniworld/blob/master/pytorch-a2c-ppo-acktr/vec_env/subproc_vec_env.py#L2
> https://github.com/maximecb/gym-miniworld/blob/master/pytorch-a2c-ppo-acktr/vec_env/subproc_vec_env.py#L39
> 
> This changes something in the way resources are shared between subprocesses I believe.

A problem with this modifications is that it doesn't make MiniGrid working anymore.
