### ISSUE TITLE
problems when using recent numpy 1.21.5, had to downgrade to lower numpy 1.18

### ISSUE THREAD

**Issue by ibagur** [maximecb/gym-miniworld#51]
After installing Miniworld on my virtual environment (Python 3.7.9), several errors appeared while running the `main.py` ppo training script. Apparently it was related to the `numpy 1.21.5` library I had installed by default using `pip install numpy`) on my virtual environment. I then tried to downgrade numpy to a lower version (`numpy 1.18.5`) and everything worked fine. Could you test this on your side? Thanks!

**Comment by maximecb** [comment]
Hello, could you paste the error message you got? Ideally we'd fix the issue so it works with the latest numpy.

**Comment by ibagur** [comment]
I reverted back to `numpy 1.21.5`and tried to run the training script:

`python3 main.py --algo ppo --num-frames 5000000 --num-processes 16 --num-steps 80 --lr 0.00005 --env-name MiniWorld-Hallway-v0`

The script apparently starts to run, but then this error appears:

```
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Falling back to non-multisampled frame buffer
Creating frame stacking wrapper
Saving model

/Users/inigo/.local/share/virtualenvs/miniworld-h_i21RH7/lib/python3.7/site-packages/numpy/core/_methods.py:163: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  arr = asanyarray(a)
/Users/inigo/.local/share/virtualenvs/miniworld-h_i21RH7/lib/python3.7/site-packages/numpy/core/_methods.py:163: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asanyarray(a)
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    main()
  File "main.py", line 163, in main
    np.mean(episode_rewards),
  File "<__array_function__ internals>", line 6, in mean
  File "/Users/inigo/.local/share/virtualenvs/miniworld-h_i21RH7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3441, in mean
    out=out, **kwargs)
  File "/Users/inigo/.local/share/virtualenvs/miniworld-h_i21RH7/lib/python3.7/site-packages/numpy/core/_methods.py", line 189, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'
```

**Comment by maximecb** [comment]
Might need your help to fix this. I haven't touched PyTorch code in a while. If someone has a working fix, please open a pull request.
