### ISSUE TITLE
can not run run_test.py

### ISSUE THREAD

**Issue by hickey23** [maximecb/gym-miniworld#54]
Hello, I connected ubantu server via ssh, I installed the corresponding library as you instructed, when I run with command: xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" . When /run_tests.py goes to run the file run_test.py, the following error appears:
Falling back to num_samples=1
Falling back to num_samples=1
Traceback (most recent call last):
   File "/home/lab1207/liujiong/gym-miniworld-master/./run_tests.py", line 15, in <module>
     obs, _, _, _ = env.step(0)
   File "/home/lab1207/anaconda3/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 10, in step
     assert self._has_reset, "Cannot call env.step() before calling reset()"
AssertionError: Cannot call env.step() before calling reset()

Hope to get your answer, thank you very much!

**Comment by hickey23** [comment]
sorry, I made a mistake ,the command is as follows:
xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.py

**Comment by whwang8** [comment]
I believe you have to add an env.reset() before the call to fix this!

**Comment by maximecb** [comment]
Before which call?

**Comment by hickey23** [comment]
> 我相信你必须在调用之前添加一个 env.reset() 来解决这个问题！

thank you!!! 
I got it
